include mk/var.mk
include mk/version.mk
include mk/cross.mk
include mk/dirs.mk
include mk/tool.mk
include mk/src.mk
include mk/cfg.mk
include mk/all.mk
include mk/emu.mk
include mk/format.mk
include mk/rule.mk
include mk/doc.mk
include mk/package.mk
include mk/gcc.mk
include mk/kernel.mk
include mk/install.mk
